nFFT=64;
nDSC=52;
nBitPerSym=52;
nSym=10^4;
EbN0db=0:10;
EsN0db=EbN0db+10*log10(nDSC/nFFT)+10*log10(64/80);
for ii=1:length(EbN0db)
    ipBit=rand(1,nBitPerSym*nSym)>0.5;
    ipMod=2*ipBit-1;
    ipMod=reshape(ipMod,nBitPerSym,nSym).';
    xF=[zeros(nSym,6),ipMod(:,1:nBitPerSym/2),zeros(nSym,1),ipMod(:,nBitPerSym/2+1:nBitPerSym),zeros(nSym,5)];
    xt=(nFFT/sqrt(nDSC))*ifft(fftshift(xF.')).';
    xt=[xt(:,49:64) xt];
    xt=reshape(xt.',1,nSym*80);
    nt=(1/sqrt(2))*(randn(1,nSym*80)+1j*randn(1,nSym*80));
    yt=sqrt(80/64)*xt+10.^(-EsN0db(ii)/20)*nt;
    yt=reshape(yt.',80,nSym).';
    yt= yt(:,17:80);
    yF=(sqrt(nDSC)/nFFT)*fftshift(fft(yt.')).';
    yMod=yF(:,[6+(1:nBitPerSym/2),7+(nBitPerSym/2+1:nBitPerSym)]);
    ipModHat=2*floor(real(yMod/2))+1;
    ipModHat(ipModHat>1)=1;
    ipModHat(ipModHat<-1)=-1;
    ipBitHat=(ipModHat+1)/2;
    ipBitHat=reshape(ipBitHat.',nBitPerSym*nSym,1).';
    nErr(ii)=sum(ipBitHat~=ipBit);
end
simBER=nErr/(nBitPerSym*nSym);
theoryBER=(1/2)*erfc(sqrt(10.^(EbN0db/10)));
figure;
semilogy(EbN0db,theoryBER,'bs-','LineWidth',2);
hold on;
semilogy(EbN0db,simBER,'mx-','LineWidth',2);
axis([0 10 10^-5 1]);
grid on;
legend('Theory','Simulation');
title("Bit Error Probability curve of BPSK using OFDM");
xlabel("EbN0 (dB)");
ylabel("Bit Error Rate");